ARG BASE_IMAGE 
ARG DOWNLOAD_IMAGE=download

FROM ${BASE_IMAGE} AS download

RUN mkdir -p /workspace/build_deps/{apt,python,src}

ENV APT_DEPS="strace valgrind htop nvtop atop ioping fio tree"

RUN cd /workspace/build_deps/apt \
  && apt-get update \
  && apt-get install -y --download-only --no-install-recommends ${APT_DEPS} \
  && mv /var/cache/apt/archives/*.deb ./

ENV NCCL_TESTS_VERSION=2.15.0
RUN cd /workspace/build_deps/src \
    && wget -O nccl-tests-${NCCL_TESTS_VERSION}.tar.gz https://github.com/NVIDIA/nccl-tests/archive/refs/tags/v${NCCL_TESTS_VERSION}.tar.gz

WORKDIR /workspace/BrainBERT

COPY . /workspace/BrainBERT

RUN cd /workspace/build_deps/python \
  && pip download --dest . -v --no-build-isolation --no-cache --no-dependencies \
    pytorch-ranger torch-optimizer \
  && grep -v 'torch_optimizer'  /workspace/BrainBERT/requirements.txt | \
    pip download --dest . -v --no-build-isolation --no-cache -r /dev/stdin

FROM ${DOWNLOAD_IMAGE} AS download-copy

FROM ${BASE_IMAGE} AS build-offline

COPY --from=download-copy /workspace/build_deps /workspace/build_deps

COPY --from=download-copy /workspace/BrainBERT /workspace/BrainBERT

RUN apt-get update \
  && apt-get install -yqq --no-install-recommends /workspace/build_deps/apt/*.deb \
  && rm -rf /var/lib/apt/lists/* \
  && rm -r /workspace/build_deps/apt

RUN cd /workspace/build_deps/src \
    && NCCL_TESTS_VERSION=$(ls nccl-tests-*.tar.gz | sed -e 's/nccl-tests-//' -e 's/.tar.gz//') \
    && tar xf nccl-tests-${NCCL_TESTS_VERSION}.tar.gz \
    && cd nccl-tests-${NCCL_TESTS_VERSION} \
    && MPI=1 MPI_HOME=/opt/hpcx/ompi make -j$(nproc) \
    && cd .. \
    && rm -rf nccl-tests-${NCCL_TESTS_VERSION}.tar.gz

WORKDIR /workspace/BrainBERT

RUN pip install -v --no-build-isolation \
    --no-index --find-links=/workspace/build_deps/python \
    -r requirements-offline.txt \
    && rm -rf /workspace/build_deps
