ARG BASE_IMAGE 
FROM ${BASE_IMAGE}

ENV APT_DEPS="strace valgrind htop nvtop atop ioping fio tree"
RUN apt-get update \
  && apt-get install -yqq --no-install-recommends ${APT_DEPS} \
  && rm -rf /var/lib/apt/lists/*

ENV NCCL_TESTS_VERSION=2.15.0
RUN wget -O nccl-tests-${NCCL_TESTS_VERSION}.tar.gz https://github.com/NVIDIA/nccl-tests/archive/refs/tags/v${NCCL_TESTS_VERSION}.tar.gz \
    && tar xf nccl-tests-${NCCL_TESTS_VERSION}.tar.gz \
    && cd nccl-tests-${NCCL_TESTS_VERSION} \
    && MPI=1 MPI_HOME=/opt/hpcx/ompi make -j$(nproc) \
    && cd .. \
    && rm -rf nccl-tests-${NCCL_TESTS_VERSION}.tar.gz

WORKDIR /workspace/BrainBERT

COPY . /workspace/BrainBERT

RUN pip install -v --no-build-isolation --no-cache --no-dependencies \
      pytorch-ranger torch-optimizer \
    && grep -v 'torch_optimizer' requirements.txt | \
    pip install -v --no-build-isolation --no-cache \
      -r /dev/stdin
